name: Automate Issue and PR Responses

on:
  issues:
    types:
      - opened
      - closed
  pull_request:
    types:
      - opened
      - closed

jobs:
  respond-to-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Respond to new issues
      - name: Respond to new issues
        if: ${{ github.event.action == 'opened' && github.event_name == 'issues' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hey @${{ github.actor }}, Welcome to ğŸ’–TelMedSphere !!! ğŸŠ
            Thanks for opening an issue! ğŸ™Œ Please wait for the issue to get reviewed, if it is relevant then it will get assigned to you.
            Happy Coding !!! âœ¨

      # Respond to closed issues
      - name: Respond to closed issues
        if: ${{ github.event.action == 'closed' && github.event_name == 'issues' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}! Your issue #${{ github.event.issue.number }} has been closed.
            Thank you for interest in ğŸ’–TelMedSphere !!! ğŸ™Œ

      # Respond to new PRs
      - name: Respond to new PRs
        if: ${{ github.event.action == 'opened' && github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hey @${{ github.actor }}, Welcome to ğŸ’–TelMedSphere !!! ğŸŠ
            Thanks for raising PR, Your effort makes this project better. ğŸ™Œ
            Please wait for the PR to be reviewed.
            Happy Coding!! âœ¨

      # Respond to merged PRs
      - name: Respond to merged PRs
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.event.pull_request.user.login }} Congrats, Your pull request has been successfully merged ğŸ¥³ğŸ‰
            Thank you for your contribution to ğŸ’–TelMedSphere !!!
            Happy coding ğŸŠ, Keep Contributing ğŸ™Œ !!!
